-- Crea la tabla roles
CREATE TABLE IF NOT EXISTS roles (
    id INT PRIMARY KEY AUTO_INCREMENT,  -- Use AUTO_INCREMENT in H2
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE SCHEMA IF NOT EXISTS TASK_MANAGEMENT;

CREATE TABLE IF NOT EXISTS TASK_MANAGEMENT.TASKS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    priority INT NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    done BOOLEAN DEFAULT FALSE
);
